name: sorting_ceremony
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.9.0
  flutter: ">=3.32.5"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  i18n:
    path: ../i18n
  auth:
    path: ../auth
  ui:
    path: ../ui
  firebase_auth: ^6.1.0
  cloud_functions: ^6.0.2
  injectable: ^2.5.2
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.9.0
  injectable_generator: ^2.9.0

flutter:
  uses-material-design: true
