from firebase_functions.options import set_global_options
from firebase_admin import initialize_app

set_global_options(max_instances=5, memory=512, timeout_sec=300)

initialize_app()

from features.facade.sessionize import fetch_from_sessionize
from features.sessions.toggle_favorite_session import toggle_favorite_session
from features.rooms.manage_room import add_room_delay
from features.user.t_shirt_pickup import t_shirt_pickup
from features.points.user_points_sentinel import user_points_sentinel
from features.points.scan_other_attendee import scan_other_team_attendee
from features.points.submit_answer import submit_answer
from features.points.assign_points import assign_points
from features.sorting_ceremony.teams_members_sync import on_team_member_created
from features.sorting_ceremony.teams_members_sync import on_team_member_deleted
from features.sorting_ceremony.sorting_ceremony import sorting_ceremony

# SCHEDULE
from features.user.t_shirt_notification_schedule import t_shirt_notification_schedule
