name: media_manager
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.5.3
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  i18n:
    path: ../i18n
  auth:
    path: ../auth
  ui:
    path: ../ui

  firebase_crashlytics: ^4.1.3
  get_it: ^8.0.1
  injectable: ^2.5.0
  equatable: ^2.0.5
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  image_picker: ^1.1.2
  firebase_storage: ^12.3.4
  cloud_firestore: ^5.4.4
  path: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true
