name: media_manager
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.9.0
  flutter: ">=3.32.5"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  i18n:
    path: ../i18n
  auth:
    path: ../auth
  ui:
    path: ../ui

  firebase_crashlytics: ^5.0.3
  get_it: ^8.2.0
  injectable: ^2.5.2
  equatable: ^2.0.7
  bloc: ^9.0.1
  flutter_bloc: ^9.1.1
  image_picker: ^1.2.0
  firebase_storage: ^13.0.2
  cloud_firestore: ^6.0.3
  path: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.9.0
  injectable_generator: ^2.9.0

flutter:
  uses-material-design: true
