name: ui
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.3
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  i18n:
    path: ../i18n
  assets:
    path: ../assets
  get_it: ^8.0.2
  injectable: ^2.5.0
  firebase_auth: ^5.3.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  reactive_forms: ^17.0.1
  rive: ^0.13.15
  qr_flutter: ^4.1.0
  shorebird_code_push: ^1.1.6
  package_info_plus: ^8.1.1
  confetti: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true
  assets:
    - packages/assets/logo/logo.png
    - packages/assets/images/background.svg