name: ui
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.7.2
  flutter: ">=3.29.2"

dependencies:
  flutter:
    sdk: flutter
  i18n:
    path: ../i18n
  assets:
    path: ../assets
  get_it: ^8.0.3
  injectable: ^2.5.0
  firebase_auth: ^5.5.3
  google_fonts: ^6.2.1
  flutter_svg: ^2.1.0
  reactive_forms: ^18.0.0
  rive: ^0.13.20
  qr_flutter: ^4.1.0
  shorebird_code_push: ^2.0.3
  package_info_plus: ^8.3.0
  confetti: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  injectable_generator: ^2.7.0

flutter:
  uses-material-design: true
  assets:
    - packages/assets/logo/logo.png
    - packages/assets/images/background.svg