name: filch
sdkPath: .fvm/flutter_sdk
packages:
  - .
  - modules/**

ide:
  intellij: true

command:
  bootstrap:
    runPubGetInParallel: false
    usePubspecOverrides: true
    environment:
      sdk: ^3.5.3
      flutter: ">=3.24.0"
    dependencies:
      get_it: ^8.0.2
      injectable: ^2.5.0
      cloud_firestore: ^5.4.4
      cloud_functions: ^5.1.3
      firebase_auth: ^5.3.1
      equatable: ^2.0.5
      bloc: ^8.1.4
      flutter_bloc: ^8.1.6
      json_annotation: ^4.9.0
      collection: any
    dev_dependencies:
      flutter_lints: ^5.0.0
      build_runner: ^2.4.13
      injectable_generator: ^2.6.2
      json_serializable: ^6.8.0
  clean:
    hooks:
      post: melos exec --flutter --concurrency=1 -- "flutter clean" && find . -type f -name "*.iml" -exec rm -f {} \;

scripts:
  clean:all:
    run: flutter clean
    exec:
      concurrency: 1
      failFast: true
  remove:iml:
    run: find . -type f -name "*.iml" -exec rm -f {} \;

  generate:
    run: melos generate:i18n --no-select && melos generate:routes --no-select && melos generate:build_runner --no-select

  generate:i18n:
    run: dart pub run slang
    exec:
      failFast: true
    packageFilters:
      dependsOn:
        - slang_build_runner

  generate:build_runner:
    run: dart pub run build_runner build --delete-conflicting-outputs
    exec:
      concurrency: 1
      failFast: true
      orderDependents: true
    packageFilters:
      dependsOn:
        - build_runner

  generate:routes:
    run: dart pub run routefly
    exec:
      failFast: true
    packageFilters:
      dependsOn:
        - routefly

  lint:all:
    run: melos run format --no-select && melos run analyze --no-select

  fix:all:
    run: dart fix --apply
    exec:
      concurrency: 1
      failFast: true
      flutter: true

  test:all:
    run: melos run test --no-select

  analyze:
    run: flutter analyze . --fatal-infos
    exec:
      concurrency: 1
      failFast: true

  test:
    run: flutter test --coverage --reporter expanded
    exec:
      concurrency: 1
      failFast: true
      flutter: true
    packageFilters:
      dirExists: test

  test:update_goldens:
    run: flutter test --update-goldens --reporter expanded
    exec:
      concurrency: 1
      failFast: true
      flutter: true
    packageFilters:
      dependsOn:
        - golden_toolkit

  format:
    run: dart format -o write . --line-length=120
    exec:
      concurrency: 1
      failFast: true
      flutter: true

  generate:icon_font:
    run: /bin/zsh scripts/generate_icon_font.sh
    exec:
      failFast: true

  test:show_coverage:
    run: genhtml coverage/lcov.info -o coverage/html && open coverage/html/index.html
    exec:
      concurrency: 1
      failFast: true
    packageFilters:
      dirExists: coverage

  test:show_coverage:win:
    run: perl C:\ProgramData\chocolatey\lib\lcov\tools\bin\genhtml -o coverage\html coverage\lcov.info && start coverage\html\index.html
    exec:
      concurrency: 1
      failFast: true
    packageFilters:
      dirExists: coverage

  test:remove_generated_file_from_coverage:
    run: lcov --remove coverage/lcov.info "**/**/*.g.dart" "lib/dependency_injection/*" -o coverage/lcov.info
    exec:
      concurrency: 1
      failFast: true
    packageFilters:
      dirExists: coverage

  # build scripts ------------------------------------------------------------------------------
  build:android:aab:
    run: flutter build appbundle -t lib/main.dart --release --obfuscate --split-debug-info=bundle/debug --dart-define-from-file=.env/remote.json
    exec:
      concurrency: 1
      failFast: true
      flutter: true
    packageFilters:
      scope:
        - filch

  build:android:apk:
    run: flutter build apk -t lib/main.dart --release --obfuscate --split-debug-info=android/debug --dart-define-from-file=.env/remote.json
    exec:
      concurrency: 1
      failFast: true
      flutter: true
    packageFilters:
      scope:
        - filch

  build:ios:ipa:
    run: flutter build ipa -t lib/main.dart --release --obfuscate --split-debug-info=ios/debug --export-options-plist=ios/ExportOptions/ExportOptions.plist --dart-define-from-file=.env/remote.json
    exec:
      concurrency: 1
      failFast: true
      flutter: true
    packageFilters:
      scope:
        - filch

  shorebird:release:android:
    run: shorebird release android '--' --release --dart-define-from-file=.env/remote.json
    exec:
      concurrency: 1
      failFast: true
      flutter: true
    packageFilters:
      scope:
        - filch

  shorebird:release:ios:
    run: shorebird release ios '--' --release --export-options-plist=ios/ExportOptions/ExportOptions.plist --dart-define-from-file=.env/remote.json
    exec:
      concurrency: 1
      failFast: true
      flutter: true
    packageFilters:
      scope:
        - filch

  shorebird:release:
    run: melos shorebird:release:android --no-select && melos shorebird:release:ios --no-select

  shorebird:patch:android:
    run: shorebird patch android '--' --release --dart-define-from-file=.env/remote.json
    exec:
      concurrency: 1
      failFast: true
      flutter: true
    packageFilters:
      scope:
        - filch

  shorebird:patch:ios:
    run: shorebird patch ios '--' --release --export-options-plist=ios/ExportOptions/ExportOptions.plist --dart-define-from-file=.env/remote.json
    exec:
      concurrency: 1
      failFast: true
      flutter: true
    packageFilters:
      scope:
        - filch

  shorebird:patch:
    run: melos shorebird:patch:android --no-select && melos shorebird:patch:ios --no-select