name: filch
description: DevFest Pescara 2023 app.
publish_to: 'none'
version: 1.0.1+9

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get_it: ^7.6.4
  injectable: ^2.3.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  google_fonts: ^6.1.0
  slang: ^3.25.0
  slang_flutter: ^3.25.0
  firebase_core: ^2.22.0
  firebase_auth: ^4.14.0
  firebase_crashlytics: ^3.4.4
  cloud_functions: ^4.5.4
  cloud_firestore: ^4.13.1
  firebase_messaging: ^14.7.4
  equatable: ^2.0.5
  flutter_svg: ^2.0.9
  rive: ^0.12.3
  loggy: ^2.0.3
  flutter_loggy: ^2.0.2
  flutter_facebook_auth: ^6.0.2
  google_sign_in: ^6.1.6
  reactive_forms: ^16.1.1
  qr_flutter: ^4.1.0
  cached_network_image: ^3.3.0
  json_annotation: ^4.8.1
  mobile_scanner: ^3.5.2
  intl: ^0.18.1
  time_planner: ^0.1.2+1
  collection: ^1.18.0
  confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  injectable_generator: ^2.4.1
  slang_build_runner: ^3.25.0
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1
  melos: ^3.2.0

flutter:
  uses-material-design: true

  assets:
      - assets/images/
      - assets/images/houses/
      - assets/animations/

flutter_launcher_icons:
  android: false
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon.png"