name: filch
description: DevFest Pescara 2023 app.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get_it: ^7.6.4
  injectable: ^2.3.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  google_fonts: ^6.1.0
  slang: ^3.25.0
  slang_flutter: ^3.25.0
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  firebase_crashlytics: ^3.3.7
  cloud_functions: ^4.4.2
  cloud_firestore: ^4.9.3
  equatable: ^2.0.5
  flutter_svg: ^2.0.7
  rive: ^0.11.17
  loggy: ^2.0.3
  flutter_loggy: ^2.0.2
  flutter_facebook_auth: ^6.0.2
  reactive_forms: ^16.1.0
  qr_flutter: ^4.1.0
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  injectable_generator: ^2.4.1
  slang_build_runner: ^3.25.0
  melos: ^3.1.1

flutter:
  uses-material-design: true

  assets:
      - assets/images/
      - assets/animations/

