name: filch
description: GDG Pescara app.
publish_to: 'none'
version: 2.0.1+20

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  i18n:
    path: modules/i18n
  core:
    path: modules/core
  auth:
    path: modules/auth
  sorting_ceremony:
    path: modules/sorting_ceremony
  ui:
    path: modules/ui
  quests:
    path: modules/quests
  user:
    path: modules/user
  staff:
    path: modules/staff
  media_manager:
    path: modules/media_manager

  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  injectable: ^2.5.0
  google_fonts: ^6.2.1
  firebase_core: ^3.14.0
  firebase_messaging: ^15.2.7
  cloud_firestore: ^5.6.9
  cloud_functions: ^5.5.2
  firebase_auth: ^5.6.0
  firebase_crashlytics: ^4.3.7
  firebase_app_check: ^0.3.2+7
  loggy: ^2.0.3
  flutter_loggy: ^2.0.3+1
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  routefly: ^3.1.3
  accessibility_tools: ^2.6.0
  flutter_svg: ^2.2.0
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.3
  injectable_generator: ^2.7.0
  flutter_launcher_icons: ^0.14.4
  melos: ^6.3.3

flutter:
  uses-material-design: true
  assets:
    - shorebird.yaml
    - packages/assets/logo/logo.png
  fonts:
    - family: Digital
      fonts:
        - asset: packages/assets/fonts/Digital.ttf


flutter_launcher_icons:
  android: false
  ios: true
  remove_alpha_ios: true
  image_path: "modules/assets/lib/logo/gdg_logo_alt.png"