name: filch
description: DevFest Pescara app.
publish_to: 'none'
version: 2.0.0+11

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  i18n:
    path: modules/i18n
  core:
    path: modules/core
  auth:
    path: modules/auth
  ui:
    path: modules/ui

  cupertino_icons: ^1.0.8
  get_it: ^7.7.0
  injectable: ^2.4.2
  google_fonts: ^6.2.1
  firebase_core: ^3.1.0
  firebase_messaging: ^15.0.1
  cloud_firestore: ^5.0.1
  cloud_functions: ^5.0.1
  firebase_crashlytics: ^4.0.1
  loggy: ^2.0.3
  flutter_loggy: ^2.0.3
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  injectable_generator: ^2.6.1
  flutter_launcher_icons: ^0.13.1
  melos: ^6.0.0

flutter:
  uses-material-design: true


flutter_launcher_icons:
  android: false
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon.png"