name: filch
description: DevFest Pescara 2023 app.
publish_to: 'none'
version: 1.1.0+12

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_it: ^7.7.0
  injectable: ^2.4.2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  google_fonts: ^6.2.1
  slang: ^3.31.1
  slang_flutter: ^3.31.0
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  firebase_crashlytics: ^4.0.3
  cloud_functions: ^5.0.3
  cloud_firestore: ^5.1.0
  firebase_messaging: ^15.0.3
  equatable: ^2.0.5
  flutter_svg: ^2.0.10+1
  rive: ^0.13.9
  loggy: ^2.0.3
  flutter_loggy: ^2.0.3
  flutter_facebook_auth: ^7.0.1
  google_sign_in: ^6.2.1
  reactive_forms: ^17.0.1
  qr_flutter: ^4.1.0
  cached_network_image: ^3.3.1
  json_annotation: ^4.9.0
  mobile_scanner: ^5.1.1
  intl: ^0.19.0
  time_planner: ^0.1.2+1
  collection: ^1.18.0
  confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  injectable_generator: ^2.6.1
  slang_build_runner: ^3.31.0
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.13.1
  melos: ^6.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/houses/
    - assets/animations/
    - shorebird.yaml

flutter_launcher_icons:
  android: false
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon.png"