name: filch
description: DevFest Pescara app.
publish_to: 'none'
version: 2.0.0+14

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  i18n:
    path: modules/i18n
  core:
    path: modules/core
  auth:
    path: modules/auth
  sorting_ceremony:
    path: modules/sorting_ceremony
  ui:
    path: modules/ui
  quests:
    path: modules/quests
  user:
    path: modules/user
  staff:
    path: modules/staff

  cupertino_icons: ^1.0.8
  get_it: ^8.0.1
  injectable: ^2.5.0
  google_fonts: ^6.2.1
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  cloud_firestore: ^5.4.4
  cloud_functions: ^5.1.3
  firebase_auth: ^5.3.1
  firebase_crashlytics: ^4.1.3
  loggy: ^2.0.3
  flutter_loggy: ^2.0.3+1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  routefly: ^2.0.4
  accessibility_tools: ^2.2.3
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2
  flutter_launcher_icons: ^0.14.1
  melos: ^6.2.0

flutter:
  uses-material-design: true
  assets:
    - shorebird.yaml
    - packages/assets/logo/logo.png
  fonts:
    - family: Digital
      fonts:
        - asset: packages/assets/fonts/Digital.ttf


flutter_launcher_icons:
  android: false
  ios: true
  remove_alpha_ios: true
  image_path: "modules/assets/lib/logo/gdg_logo_small.png"