name: quests
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.9.0
  flutter: ">=3.32.5"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  i18n:
    path: ../i18n
  auth:
    path: ../auth
  ui:
    path: ../ui
  firebase_auth: ^6.1.1
  cloud_functions: ^6.0.3
  get_it: ^8.2.0
  injectable: ^2.5.2
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  cloud_firestore: ^6.0.3
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  qr_flutter: ^4.1.0
  reactive_forms: ^18.1.1
  mobile_scanner: ^7.1.2
  font_awesome_flutter: ^10.10.0
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.9.0
  injectable_generator: ^2.9.0
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true
