name: auth
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.9.0
  flutter: ">=3.32.5"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  ui:
    path: ../ui
  i18n:
    path: ../i18n
  get_it: ^8.2.0
  injectable: ^2.5.2
  equatable: ^2.0.7
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  firebase_auth: ^6.1.1
  firebase_messaging: ^16.0.3
  cloud_firestore: ^6.0.3
  google_sign_in: ^7.2.0
  reactive_forms: ^18.1.1
  font_awesome_flutter: ^10.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  mockito: ^5.5.1
  flutter_lints: ^6.0.0
  build_runner: ^2.9.0
  injectable_generator: ^2.9.0

flutter:
  uses-material-design: true