name: staff
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.8.1
  flutter: ">=3.32.5"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  ui:
    path: ../ui
  i18n:
    path: ../i18n
  auth:
    path: ../auth
  quests:
    path: ../quests
  media_manager:
    path: ../media_manager

  get_it: ^8.2.0
  injectable: ^2.5.1
  equatable: ^2.0.7
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  qr_flutter: ^4.1.0
  firebase_auth: ^6.0.0
  font_awesome_flutter: ^10.9.0
  cloud_firestore: ^6.0.0
  time_planner: ^0.1.2+1
  json_annotation: ^4.9.0
  intl: any
  collection: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.6.1
  injectable_generator: ^2.8.1
  json_serializable: ^6.10.0

flutter:
  uses-material-design: true