name: filch
description: GDG Pescara app.
publish_to: 'none'
version: 2.0.1+20

environment:
  sdk: ^3.8.1

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  i18n:
    path: ../i18n
  core:
    path: ../core
  auth:
    path: ../auth
  sorting_ceremony:
    path: ../sorting_ceremony
  ui:
    path: ../ui
  quests:
    path: ../quests
  user:
    path: ../user
  staff:
    path: ../staff
  media_manager:
    path: ../media_manager
  schedule:
    path: ../schedule

  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  injectable: ^2.5.0
  google_fonts: ^6.2.1
  firebase_core: ^3.15.1
  firebase_messaging: ^15.2.9
  cloud_firestore: ^5.6.11
  cloud_functions: ^5.6.1
  firebase_auth: ^5.6.2
  firebase_crashlytics: ^4.3.9
  firebase_app_check: ^0.3.2+8
  loggy: ^2.0.3
  flutter_loggy: ^2.0.3+1
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  routefly: ^3.1.3
  accessibility_tools: ^2.6.0
  flutter_svg: ^2.2.0
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  injectable_generator: ^2.7.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - shorebird.yaml
    - packages/assets/logo/logo.png
  fonts:
    - family: Digital
      fonts:
        - asset: packages/assets/fonts/Digital.ttf


flutter_launcher_icons:
  android: false
  ios: true
  remove_alpha_ios: true
  image_path: "packages/assets/lib/logo/gdg_logo_alt.png"