name: core
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.9.0
  flutter: ">=3.32.5"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  get_it: ^8.2.0
  injectable: ^2.5.1
  json_annotation: ^4.9.0
  cloud_firestore: ^6.0.1
  cloud_functions: ^6.0.1
  firebase_storage: ^13.0.1
  firebase_messaging: ^16.0.1
  equatable: ^2.0.7
  shared_preferences: ^2.5.3
  loggy: ^2.0.3
  package_info_plus: ^8.3.1
  bloc: ^9.0.0
  path_provider: ^2.1.5
  image_picker: ^1.2.0
  shorebird_code_push: ^2.0.4
  catch_and_flow: ^1.0.9
  path: any
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.7.0
  json_serializable: ^6.11.0
  injectable_generator: ^2.8.1

flutter:
  uses-material-design: true
