name: auth
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.3
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../../modules/core
  ui:
    path: ../../modules/ui
  i18n:
    path: ../../modules/i18n
  get_it: ^8.0.1
  injectable: ^2.5.0
  equatable: ^2.0.5
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  firebase_auth: ^5.3.1
  firebase_messaging: ^15.1.3
  cloud_firestore: ^5.4.4
  google_sign_in: ^6.2.1
  reactive_forms: ^17.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true