name: auth
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../../modules/core
  ui:
    path: ../../modules/ui
  i18n:
    path: ../../modules/i18n
  get_it: ^7.7.0
  injectable: ^2.4.2
  equatable: ^2.0.5
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  firebase_auth: ^5.1.0
  google_sign_in: ^6.2.1
  reactive_forms: ^17.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  injectable_generator: ^2.6.1

flutter:
  uses-material-design: true