name: ui
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.9.0
  flutter: ">=3.32.5"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  i18n:
    path: ../i18n
  assets:
    path: ../../packages/assets
  get_it: ^8.2.0
  injectable: ^2.5.1
  firebase_auth: ^6.0.2
  google_fonts: ^6.3.0
  flutter_svg: ^2.2.1
  reactive_forms: ^18.1.1
  rive: ^0.13.20
  qr_flutter: ^4.1.0
  shorebird_code_push: ^2.0.4
  package_info_plus: ^8.3.0
  confetti: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.7.0
  injectable_generator: ^2.8.1

flutter:
  uses-material-design: true
  assets:
    - packages/assets/logo/logo.png
    - packages/assets/images/background.svg