name: user
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.8.1
  flutter: ">=3.32.5"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  ui:
    path: ../ui
  i18n:
    path: ../i18n
  auth:
    path: ../auth
  quests:
    path: ../quests
  get_it: ^8.0.3
  injectable: ^2.5.0
  equatable: ^2.0.7
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  qr_flutter: ^4.1.0
  intl: any
  firebase_auth: ^5.6.2
  font_awesome_flutter: ^10.8.0
  cloud_firestore: ^5.6.11
  flutter_svg: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  injectable_generator: ^2.7.0

flutter:
  uses-material-design: true
  assets:
    - packages/assets/images/lines.svg
