name: user
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.9.0
  flutter: ">=3.32.5"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  ui:
    path: ../ui
  i18n:
    path: ../i18n
  auth:
    path: ../auth
  quests:
    path: ../quests
  schedule:
    path: ../schedule
  get_it: ^8.2.0
  injectable: ^2.5.2
  equatable: ^2.0.7
  bloc: ^9.0.1
  flutter_bloc: ^9.1.1
  qr_flutter: ^4.1.0
  firebase_auth: ^6.1.1
  font_awesome_flutter: ^10.10.0
  cloud_firestore: ^6.0.3
  flutter_svg: ^2.2.1
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.9.0
  injectable_generator: ^2.9.0

flutter:
  uses-material-design: true
  assets:
    - packages/assets/images/lines.svg
