name: core
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.3
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.7.0
  injectable: ^2.4.4
  json_annotation: ^4.9.0
  cloud_firestore: ^5.4.3
  cloud_functions: ^5.1.3
  equatable: ^2.0.5
  shared_preferences: ^2.3.2
  loggy: ^2.0.3
  package_info_plus: ^8.0.2
  bloc: ^8.1.4
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true
