name: quests
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.8.1
  flutter: ">=3.32.5"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  i18n:
    path: ../i18n
  auth:
    path: ../auth
  ui:
    path: ../ui
  firebase_auth: ^5.6.2
  cloud_functions: ^5.6.1
  get_it: ^8.0.3
  injectable: ^2.5.0
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  cloud_firestore: ^5.6.11
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  qr_flutter: ^4.1.0
  reactive_forms: ^18.1.1
  mobile_scanner: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
