name: schedule
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.8.1
  flutter: ">=3.32.5"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../core

  cloud_firestore: ^6.0.0
  equatable: ^2.0.7
  injectable: ^2.5.1
  json_annotation: ^4.9.0
  collection: any
  flutter_bloc: ^8.1.6
  get_it: ^8.0.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.6.1
  injectable_generator: ^2.8.1
  json_serializable: ^6.10.0
  flutter_lints: ^6.0.0
  mockito: ^5.5.0
  fake_cloud_firestore: ^4.0.0

flutter:
  uses-material-design: true