name: schedule
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.8.1
  flutter: ">=3.32.5"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0