name: schedule
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.8.1
  flutter: ">=3.32.5"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  injectable: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.4
  injectable_generator: ^2.7.0
  flutter_lints: ^6.0.0